version: '2'
services:
  grav:
    image: evns/grav
    build: ./
    ports:
      - "80:80"
    environment:
      - TERM=xterm
      - DOMAIN=localhost
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=Pa55word
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PERMISSIONS=b
      - ADMIN_FULLNAME=Admin
      - ADMIN_TITLE=SiteAdmin
    volumes:
      - /var/www/grav-admin
